// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mathematical group structure
 */
export type GroupDefinition = {
  /**
   * Name of the group
   */
  name: string;
  /**
   * Order of the group (number of elements)
   */
  order: number | null;
  /**
   * Whether the group is abelian (commutative)
   */
  is_abelian: boolean;
  /**
   * Whether the group is cyclic
   */
  is_cyclic: boolean;
  /**
   * Whether the group is finite
   */
  is_finite: boolean;
  /**
   * Symbol for the identity element
   */
  identity_symbol: string;
  /**
   * Symbol for the group operation
   */
  operation_symbol: string;
};
