// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";

export type AbstractionMetadata = {
  /**
   * Abstraction level (L1-L4) as per theory_and_render.md
   */
  level: number | null;
  /**
   * Link to the L1/L2 blueprint or source template for this object/definition.
   */
  source_template_id: string | null;
  /**
   * For L2/L3/L4, parameters that have been specified or concretized.
   */
  specified_parameters: Array<[string, MathNode]>;
  /**
   * For L2, properties that are universally quantified (or "any valid option").
   */
  universally_quantified_properties: Array<string>;
};
