// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivationMetadata } from "./DerivationMetadata";
import type { PresentationConfig } from "./PresentationConfig";
import type { SimplifiedContentStructure } from "./SimplifiedContentStructure";
import type { SourceReference } from "./SourceReference";

export type AbstractSummaryContent = {
  abstraction_level: number;
  key_properties: Array<string>;
  source_references: Array<SourceReference>;
  derivation_metadata: DerivationMetadata;
  content: SimplifiedContentStructure;
  presentation_config: PresentationConfig;
};
