// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcademicMetadata = {
  authors: Array<string>;
  date_published: string | null;
  date_modified: string | null;
  venue: string | null;
  doi: string | null;
  keywords: Array<string>;
};
