// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignmentArrow } from "./AlignmentArrow";
import type { VisualizationType } from "./VisualizationType";

export type AlignmentVisualization = {
  visualization_type: VisualizationType;
  source_elements: Array<string>;
  target_elements: Array<string>;
  alignment_arrows: Array<AlignmentArrow>;
};
