// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignmentPrecision } from "./AlignmentPrecision";

export type AlignmentType = {
  alignment_id: string;
  name: string;
  description: string | null;
  precision_level: AlignmentPrecision;
};
