// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrowStyle } from "./ArrowStyle";

export type AlignmentArrow = {
  from_concept: string;
  to_concept: string;
  alignment_strength: number;
  alignment_type: string;
  visual_style: ArrowStyle;
};
