// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnimationConfig = {
  enabled_animations: Array<string>;
  animation_speed: number;
  auto_play: boolean | null;
  show_controls: boolean | null;
};
