// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationTimeline } from "./AnimationTimeline";
import type { ControlBinding } from "./ControlBinding";
import type { InteractionPoint } from "./InteractionPoint";
import type { InteractionSystem } from "./InteractionSystem";
import type { Section } from "./Section";

export type AnimatedPresentationContent = {
  title: string;
  slide_count: number;
  auto_advance: boolean;
  base_content: Array<Section>;
  interaction_system: InteractionSystem;
  animation_timeline: AnimationTimeline;
  control_bindings: Array<ControlBinding>;
  interaction_points: Array<InteractionPoint>;
};
