// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationKeyframe } from "./AnimationKeyframe";
import type { InteractionPoint } from "./InteractionPoint";
import type { SyncGroup } from "./SyncGroup";

export type AnimationTimeline = {
  total_duration: number;
  keyframes: Array<AnimationKeyframe>;
  interaction_points: Array<InteractionPoint>;
  synchronization_groups: Array<SyncGroup>;
};
