// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationType } from "./AnimationType";
import type { EasingFunction } from "./EasingFunction";

export type AnimationKeyframe = {
  time: number;
  target_elements: Array<string>;
  animation_type: AnimationType;
  properties: { [key in string]?: string };
  easing: EasingFunction;
};
