// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnnotationStyling = {
  color: string | null;
  background_color: string | null;
  border_color: string | null;
  opacity: number | null;
};
