// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationPosition } from "./AnnotationPosition";
import type { AnnotationStyling } from "./AnnotationStyling";
import type { AnnotationType } from "./AnnotationType";
import type { RichTextSegment } from "./RichTextSegment";

export type Annotation = {
  id: string;
  target_selector: string;
  annotation_content: Array<RichTextSegment>;
  annotation_type: AnnotationType;
  position: AnnotationPosition | null;
  styling: AnnotationStyling | null;
};
