// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionAnchor } from "./PositionAnchor";

export type AnnotationPosition = {
  x: number;
  y: number;
  anchor: PositionAnchor;
};
