// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { OverlayStyle } from "./OverlayStyle";
import type { SectionContentNode } from "./SectionContentNode";

export type AnnotationOverlay = {
  base_content: Array<SectionContentNode>;
  annotations: Array<Annotation>;
  overlay_style: OverlayStyle;
};
