// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BinaryOperator =
  | "Plus"
  | "Minus"
  | "Times"
  | "Dot"
  | "Slash"
  | "Divide"
  | "SemidirectProduct"
  | "DirectProduct"
  | "Union"
  | "Intersection"
  | "CartesianProduct"
  | "And"
  | "Or"
  | "Xor"
  | { "Custom": string };
