// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of variable bindings
 */
export type BindingType =
  | "Assumption"
  | "Definition"
  | "Hypothesis"
  | "Given"
  | "Let";
