// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademicMetadata } from "./AcademicMetadata";
import type { AudienceLevel } from "./AudienceLevel";
import type { DerivationMetadata } from "./DerivationMetadata";
import type { PresentationConfig } from "./PresentationConfig";
import type { SimplifiedContentStructure } from "./SimplifiedContentStructure";
import type { SourceReference } from "./SourceReference";
import type { WritingStyle } from "./WritingStyle";

export type BlogPostContent = {
  title: string;
  writing_style: WritingStyle;
  target_audience: AudienceLevel;
  examples_included: boolean;
  source_references: Array<SourceReference>;
  derivation_metadata: DerivationMetadata;
  content: SimplifiedContentStructure;
  presentation_config: PresentationConfig;
  academic_metadata: AcademicMetadata | null;
};
