// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchingNode } from "./BranchingNode";
import type { ContainerLayout } from "./ContainerLayout";
import type { ContainerType } from "./ContainerType";

/**
 * Abstract container for representing any hierarchical, branching structure
 * Can represent ProofForest, storyboards, multiverse narratives, etc.
 */
export type BranchingContainer = {
  container_id: string;
  container_type: ContainerType;
  nodes: Array<BranchingNode>;
  layout_config: ContainerLayout | null;
  container_metadata: Array<[string, string]>;
};
