// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeState } from "./NodeState";
import type { NodeType } from "./NodeType";
import type { SectionContentNode } from "./SectionContentNode";

/**
 * Individual node in a branching container
 */
export type BranchingNode = {
  node_id: string;
  parent_id: string | null;
  node_type: NodeType;
  content: Array<SectionContentNode>;
  node_metadata: Array<[string, string]>;
  children: Array<string>;
  node_state: NodeState;
};
