// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Goal } from "./Goal";
import type { MathNode } from "./MathNode";

/**
 * Represents a case in case analysis
 */
export type Case = {
  condition: MathNode;
  proof: Goal;
  case_name: string | null;
};
