// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChapterInfo = {
  chapter_number: number | null;
  chapter_title: string;
  prerequisites: Array<string>;
  learning_objectives: Array<string>;
};
