// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";

export type CodeBlockNode = {
  code: string;
  language: string | null;
  caption: RichText | null;
  show_line_numbers: boolean | null;
  highlight_lines: Array<number>;
  is_executable: boolean | null;
};
