// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParagraphNode } from "./ParagraphNode";

export type CodeBlockNode = {
  code: string;
  language: string | null;
  caption: ParagraphNode | null;
  show_line_numbers: boolean | null;
  highlight_lines: Array<number> | null;
  is_executable: boolean | null;
};
