// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichTextSegment } from "./RichTextSegment";
import type { SectionContentNode } from "./SectionContentNode";

export type CollapsibleBlockNode = {
  summary: Array<RichTextSegment>;
  details: Array<SectionContentNode>;
  initially_collapsed: boolean | null;
};
