// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextAlignment } from "./TextAlignment";

export type ColumnStyle = {
  width: string | null;
  alignment: TextAlignment | null;
};
