// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionContentNode } from "./SectionContentNode";

export type ColumnsNode = {
  columns_content: Array<Array<SectionContentNode>>;
  column_widths: Array<string>;
  gap: string | null;
};
