// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichTextSegment } from "./RichTextSegment";
import type { SectionContentNode } from "./SectionContentNode";

export type ComparisonSection = {
  section_id: string;
  left_content: Array<SectionContentNode>;
  right_content: Array<SectionContentNode>;
  comparison_notes: Array<RichTextSegment> | null;
};
