// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonCriterion } from "./ComparisonCriterion";
import type { ComparisonStructure } from "./ComparisonStructure";
import type { RelationshipMetadata } from "./RelationshipMetadata";
import type { TheoryReference } from "./TheoryReference";

export type ComparisonPageContent = {
  title: string;
  comparison_criteria: Array<ComparisonCriterion>;
  highlight_differences: boolean;
  synchronized_navigation: boolean;
  theories_involved: Array<TheoryReference>;
  relationship_metadata: RelationshipMetadata;
  comparison_structure: ComparisonStructure;
};
