// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ComparisonCriterion = {
  criterion_id: string;
  name: string;
  description: string | null;
  weight: number | null;
};
