// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComparisonLayout } from "./ComparisonLayout";
import type { ComparisonSection } from "./ComparisonSection";

export type ComparisonStructure = {
  comparison_type: string;
  layout: ComparisonLayout;
  sections: Array<ComparisonSection>;
};
