// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConceptRelationType } from "./ConceptRelationType";

export type ConceptRelationship = {
  source_concept: string;
  target_concept: string;
  relationship_type: ConceptRelationType;
  description: string | null;
};
