// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrespondenceType } from "./CorrespondenceType";

export type ConceptCorrespondence = {
  source_concept: string;
  target_concept: string;
  correspondence_type: CorrespondenceType;
  confidence: number | null;
};
