// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignmentType } from "./AlignmentType";
import type { AlignmentVisualization } from "./AlignmentVisualization";
import type { ConceptCorrespondence } from "./ConceptCorrespondence";
import type { RelationshipMetadata } from "./RelationshipMetadata";
import type { TheoryReference } from "./TheoryReference";

export type ConceptAlignmentContent = {
  title: string;
  alignment_type: AlignmentType;
  correspondence_mappings: Array<ConceptCorrespondence>;
  theories_involved: Array<TheoryReference>;
  relationship_metadata: RelationshipMetadata;
  alignment_visualizations: Array<AlignmentVisualization>;
};
