// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextPreservationLevel } from "./ContextPreservationLevel";
import type { ExtractionMetadata } from "./ExtractionMetadata";
import type { InteractionLevel } from "./InteractionLevel";
import type { ViewportConfig } from "./ViewportConfig";

export type ConceptExtractContent = {
  source_document_id: string;
  extracted_concepts: Array<string>;
  context_preservation: ContextPreservationLevel;
  extraction_metadata: ExtractionMetadata;
  viewport_config: ViewportConfig;
  interaction_level: InteractionLevel;
};
