// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConceptRelationType } from "./ConceptRelationType";

export type ConceptReference = {
  concept_id: string;
  relationship_type: ConceptRelationType;
  strength: number;
};
