// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConstraintType } from "./ConstraintType";

export type Constraint = {
  constraint_type: ConstraintType;
  parameters_involved: Array<string>;
  formula: string;
};
