// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Context where an expression appears
 */
export type ContextType =
  | "Goal"
  | "Hypothesis"
  | "Premise"
  | "Axiom"
  | "Theorem"
  | "Definition"
  | "Assumption";
