// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextPreservationLevel = {
  level_name: string;
  preserve_structure: boolean;
  preserve_formatting: boolean;
  preserve_links: boolean;
  preserve_metadata: boolean;
};
