// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ControlType =
  | { "Slider": { min: number; max: number; step: number } }
  | "Toggle"
  | { "Dropdown": { options: Array<string> } }
  | { "NumberInput": { min: number | null; max: number | null } }
  | "ColorPicker"
  | { "Button": { action: string } }
  | { "RadioGroup": { options: Array<string> } };
