// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of branching containers
 */
export type ContainerType =
  | "ProofForest"
  | "Storyboard"
  | "Multiverse"
  | "DecisionTree"
  | "Workflow"
  | "MindMap"
  | "Timeline"
  | { "Custom": string };
