// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionHandler } from "./InteractionHandler";
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Display container for context variable
 */
export type ContextVariableDisplay = {
  variable_name: MathNode;
  variable_type: RichText;
  is_highlighted: boolean;
  interaction_handlers: Array<InteractionHandler>;
};
