// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentMetadata = {
  language: string | null;
  version: string | null;
  created_at: string | null;
  last_modified: string | null;
  content_hash: string | null;
};
