// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlType } from "./ControlType";

export type Control = {
  id: string;
  label: string;
  control_type: ControlType;
  parameter_name: string;
  default_value: string;
  description: string | null;
};
