// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ValueTransformation } from "./ValueTransformation";

export type ControlBinding = {
  control_id: string;
  target_variable: string;
  transformation: ValueTransformation | null;
};
