// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutAlignment } from "./LayoutAlignment";
import type { LayoutDirection } from "./LayoutDirection";
import type { LayoutType } from "./LayoutType";

/**
 * Layout configuration for branching containers
 */
export type ContainerLayout = {
  layout_type: LayoutType;
  direction: LayoutDirection;
  spacing: string | null;
  alignment: LayoutAlignment | null;
  max_depth: number | null;
  collapse_branches: boolean | null;
};
