// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionContentNode } from "./SectionContentNode";

export type CoreExample = {
  example_id: string;
  title: string;
  content: Array<SectionContentNode>;
  difficulty_level: string | null;
  concepts_illustrated: Array<string>;
};
