// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrossReferenceType } from "./CrossReferenceType";

export type CrossReference = {
  reference_id: string;
  target_id: string;
  reference_type: CrossReferenceType;
  display_text: string | null;
};
