// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyEdge } from "./DependencyEdge";
import type { DependencyNode } from "./DependencyNode";

export type DependencyGraph = {
  nodes: Array<DependencyNode>;
  edges: Array<DependencyEdge>;
  graph_metadata: { [key in string]?: string } | null;
};
