// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyNodeType } from "./DependencyNodeType";

export type DependencyNode = {
  node_id: string;
  content_id: string;
  node_type: DependencyNodeType;
};
