// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyType } from "./DependencyType";

export type DependencyEdge = {
  from_node: string;
  to_node: string;
  dependency_type: DependencyType;
  strength: number | null;
};
