// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccuracyMetrics } from "./AccuracyMetrics";

export type DerivationMetadata = {
  derived_at: string;
  derivation_rules: Array<string>;
  human_reviewed: boolean;
  accuracy_metrics: AccuracyMetrics | null;
};
