// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectionType } from "./DirectionType";

export type Direction = { direction_type: DirectionType; angle: number | null };
