// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BibEntry } from "./BibEntry";
import type { Section } from "./Section";
import type { TocNode } from "./TocNode";

export type DocumentStructure = {
  abstract_content: Section | null;
  table_of_contents: TocNode | null;
  body: Array<Section>;
  footnotes: Array<Section>;
  glossary: Array<Section>;
  bibliography: Array<BibEntry>;
};
