// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Legacy DocumentType enum for backwards compatibility
 */
export type DocumentType =
  | "ScientificPaper"
  | "Textbook"
  | "WikiPage"
  | "PersonalNotes"
  | "BlogPost"
  | "TooltipSummary"
  | "AnimatedPresentation"
  | "TypeMappingDisplay"
  | "ComparisonPage"
  | "TransformationMapping"
  | "InteractivePlayground"
  | "MathematicianNotes"
  | "StudyNotes"
  | "ResourcePanel";
