// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConceptReference } from "./ConceptReference";
import type { CrossReference } from "./CrossReference";
import type { DependencyGraph } from "./DependencyGraph";

export type DocumentRelationships = {
  parent_documents: Array<string>;
  child_documents: Array<string>;
  related_concepts: Array<ConceptReference>;
  cross_references: Array<CrossReference>;
  dependency_graph: DependencyGraph | null;
};
