// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to another mathematical object, potentially in a different domain
 */
export type DomainReference = {
  /**
   * Domain the referenced object belongs to
   */
  domain: string;
  /**
   * Type of the referenced object
   */
  object_type: string;
  /**
   * ID of the referenced object
   */
  object_id: string;
  /**
   * Display name (for UI purposes)
   */
  display_name: string;
  /**
   * Brief description for hover text
   */
  hover_description: string | null;
  /**
   * LaTeX representation for display
   */
  latex: string | null;
};
