// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EasingType } from "./EasingType";

export type EasingFunction = {
  function_type: EasingType;
  parameters: Array<number> | null;
};
