// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Elimination methods for logical rules
 */
export type EliminationMethod =
  | "ModusPonens"
  | "ModusTollens"
  | "DisjunctiveSyllogism"
  | "UniversalInstantiation"
  | "ExistentialInstantiation";
