// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichTextSegment } from "./RichTextSegment";

export type EssentialDefinition = {
  term: string;
  simplified_definition: Array<RichTextSegment>;
  formal_definition: MathNode | null;
  intuitive_explanation: Array<RichTextSegment> | null;
};
