// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionAction } from "./InteractionAction";

export type EventHandler = {
  event_type: string;
  target_selector: string;
  action: InteractionAction;
};
