// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextType } from "./ContextType";

/**
 * Position of an expression within a proof node
 */
export type ExpressionPosition = {
  node_id: string;
  context_type: ContextType;
  index: number | null;
  path: Array<string>;
};
