// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractionMetadata = {
  extracted_at: string;
  extraction_method: string;
  source_version: string | null;
  extraction_rules: Array<string>;
  quality_metrics: { [key in string]?: number } | null;
};
