// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Failed attempt in automated search
 */
export type FailedAttempt = {
  tactic_name: RichText;
  failure_reason: RichText;
  goal_state: MathNode;
  error_details: RichText | null;
};
