// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterType } from "./FilterType";

export type FilterOption = {
  name: string;
  filter_type: FilterType;
  options: Array<string>;
};
