// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visual styles for goals
 */
export type GoalVisualStyle =
  | "Standard"
  | "Highlighted"
  | "Focused"
  | "Completed";
