// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalType } from "./GoalType";
import type { MathNode } from "./MathNode";
import type { QuantifiedObject } from "./QuantifiedObject";
import type { VariableBinding } from "./VariableBinding";

/**
 * Represents a structured proof goal with proper mathematical formatting
 */
export type Goal = {
  quantified_objects: Array<QuantifiedObject>;
  variable_bindings: Array<VariableBinding>;
  statement: MathNode;
  goal_type: GoalType;
};
