// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextVariableDisplay } from "./ContextVariableDisplay";
import type { GoalVisualStyle } from "./GoalVisualStyle";
import type { MathNode } from "./MathNode";

/**
 * Display container for proof goal
 */
export type GoalDisplay = {
  context_variables: Array<ContextVariableDisplay>;
  goal_statement: MathNode;
  visual_style: GoalVisualStyle;
};
