// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionContentNode } from "./SectionContentNode";

export type GridItemNode = {
  content: SectionContentNode;
  col_start: number | null;
  col_end: number | null;
  row_start: number | null;
  row_end: number | null;
};
