// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridItemNode } from "./GridItemNode";

export type GridNode = {
  items: Array<GridItemNode>;
  /**
   * Number of columns, or CSS grid-template-columns string.
   */
  column_template: string;
  row_gap: string | null;
  column_gap: string | null;
};
