// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group homomorphism
 */
export type GroupHomomorphism = {
  /**
   * Name of the homomorphism
   */
  name: string;
  /**
   * Domain (source) group
   */
  domain: string;
  /**
   * Codomain (target) group
   */
  codomain: string;
  /**
   * Whether this is an isomorphism
   */
  is_isomorphism: boolean;
  /**
   * Whether this is a monomorphism (injective)
   */
  is_monomorphism: boolean;
  /**
   * Whether this is an epimorphism (surjective)
   */
  is_epimorphism: boolean;
  /**
   * Whether this is an endomorphism (domain = codomain)
   */
  is_endomorphism: boolean;
  /**
   * Whether this is an automorphism (isomorphism with domain = codomain)
   */
  is_automorphism: boolean;
};
