// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A group element
 */
export type GroupElement = {
  /**
   * Symbol or name for this element
   */
  symbol: string;
  /**
   * Order of this element in the group
   */
  order: number | null;
  /**
   * Whether this element is the identity
   */
  is_identity: boolean;
  /**
   * Whether this element is an involution (self-inverse)
   */
  is_involution: boolean;
  /**
   * Symbol for the inverse of this element
   */
  inverse_symbol: string | null;
};
