// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptNode } from "./ScriptNode";
import type { SpecialMiddleScriptNode } from "./SpecialMiddleScriptNode";

export type IdentifierNode = {
  body: string;
  pre_script: ScriptNode | null;
  mid_script: SpecialMiddleScriptNode | null;
  post_script: ScriptNode | null;
  primes: number;
  is_function: boolean;
};
