// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionMetadata } from "./ExtractionMetadata";
import type { InteractionLevel } from "./InteractionLevel";
import type { SandboxPermission } from "./SandboxPermission";
import type { ViewportConfig } from "./ViewportConfig";

export type IFrameEmbedContent = {
  source_document_id: string;
  sandbox_permissions: Array<SandboxPermission>;
  responsive_scaling: boolean;
  extraction_metadata: ExtractionMetadata;
  viewport_config: ViewportConfig;
  interaction_level: InteractionLevel;
};
