// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HorizontalAlignment } from "./HorizontalAlignment";
import type { ParagraphNode } from "./ParagraphNode";

export type ImageNode = {
  src: string;
  alt_text: string | null;
  caption: ParagraphNode | null;
  width: string | null;
  height: string | null;
  alignment: HorizontalAlignment | null;
};
