// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstantiationDirection } from "./InstantiationDirection";
import type { MathNode } from "./MathNode";

/**
 * Represents an instantiation map for variable substitution
 */
export type InstantiationMap = {
  variable_name: string;
  instantiated_value: MathNode;
  source_expression: string;
  target_expression: string;
  direction: InstantiationDirection;
};
