// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction of instantiation
 */
export type InstantiationDirection = "Forward" | "Backward" | "Bidirectional";
