// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionPosition } from "./ExpressionPosition";
import type { MathNode } from "./MathNode";
import type { ProofExpressionInteractionType } from "./ProofExpressionInteractionType";

/**
 * Represents a single expression that can be interacted with
 */
export type InteractiveExpression = {
  id: string;
  expression: MathNode;
  position: ExpressionPosition;
  interaction_type: ProofExpressionInteractionType;
  metadata: { [key in string]?: string };
};
