// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionPosition } from "./ExpressionPosition";
import type { InteractionHandler } from "./InteractionHandler";
import type { InteractiveElementType } from "./InteractiveElementType";
import type { MathNode } from "./MathNode";

/**
 * Represents an interactive element that can be highlighted or selected
 */
export type InteractiveElement = {
  id: string;
  element_type: InteractiveElementType;
  expression: MathNode | null;
  text: string | null;
  position: ExpressionPosition;
  interaction_handlers: Array<InteractionHandler>;
};
