// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InteractionType =
  | "PauseForClick"
  | "RequireHover"
  | "WaitForInput"
  | { "BranchingChoice": { options: Array<string> } }
  | { "ParameterAdjustment": { parameter_name: string } };
