// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionType } from "./InteractionType";
import type { UserAction } from "./UserAction";

export type InteractionPoint = {
  time: number;
  interaction_type: InteractionType;
  target_element: string;
  required_action: UserAction;
  timeout: number | null;
};
