// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandlerType } from "./HandlerType";

/**
 * Represents an interaction handler for an element
 */
export type InteractionHandler = {
  handler_type: HandlerType;
  action: string;
  parameters: { [key in string]?: string };
};
