// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParagraphNode } from "./ParagraphNode";

export type InteractiveDiagramNode = {
  diagram_type_id: string;
  data: string;
  caption: ParagraphNode | null;
  config_options: string | null;
};
