// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";
import type { EventHandler } from "./EventHandler";
import type { StateVariable } from "./StateVariable";

export type InteractionSystem = {
  controls: Array<Control>;
  event_handlers: Array<EventHandler>;
  state_variables: Array<StateVariable>;
};
