// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofForestDisplay } from "./ProofForestDisplay";
import type { ProofInteractionConfig } from "./ProofInteractionConfig";
import type { ProofTransformationData } from "./ProofTransformationData";
import type { ProofVisualConfig } from "./ProofVisualConfig";

/**
 * Display container for interactive proof visualization
 */
export type InteractiveProofDisplay = {
  id: string;
  title: string;
  proof_forest: ProofForestDisplay;
  transformation_data: Array<ProofTransformationData>;
  visual_config: ProofVisualConfig;
  interaction_config: ProofInteractionConfig;
};
