// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InteractionAction =
  | { "UpdateParameter": { parameter: string; value: string } }
  | { "TriggerAnimation": { animation_id: string } }
  | { "NavigateToSlide": { slide_index: number } }
  | { "ShowTooltip": { content: string } }
  | { "HighlightElement": { element_id: string } };
