// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationTimeline } from "./AnimationTimeline";
import type { ControlBinding } from "./ControlBinding";
import type { InteractionSystem } from "./InteractionSystem";
import type { ParameterSpace } from "./ParameterSpace";
import type { Section } from "./Section";
import type { VisualizationType } from "./VisualizationType";

export type InteractivePlaygroundContent = {
  title: string;
  parameter_space: ParameterSpace;
  visualization_types: Array<VisualizationType>;
  real_time_feedback: boolean;
  base_content: Array<Section>;
  interaction_system: InteractionSystem;
  control_bindings: Array<ControlBinding>;
  animation_timeline: AnimationTimeline | null;
};
