// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of interactive elements
 */
export type InteractiveElementType =
  | "Variable"
  | "Expression"
  | "Hypothesis"
  | "Goal"
  | "Tactic"
  | "Axiom"
  | "Theorem"
  | "Pattern"
  | "Instantiation";
