// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";
import type { ControlLayout } from "./ControlLayout";

export type InteractiveControls = {
  controls: Array<Control>;
  target_content_ids: Array<string>;
  layout: ControlLayout;
};
