// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogicalNode } from "./LogicalNode";
import type { QuantifiedVariableDeclarationGroup } from "./QuantifiedVariableDeclarationGroup";
import type { VariableDeclaration } from "./VariableDeclaration";

export type Judgement = {
  non_quantifiers: Array<VariableDeclaration>;
  quantifiers: Array<QuantifiedVariableDeclarationGroup>;
  statement: LogicalNode;
};
