// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportanceLevel } from "./ImportanceLevel";
import type { RichTextSegment } from "./RichTextSegment";

export type KeyPoint = {
  id: string;
  content: Array<RichTextSegment>;
  importance_level: ImportanceLevel;
  source_section_id: string | null;
};
