// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of layout for branching containers
 */
export type LayoutType =
  | "Tree"
  | "Radial"
  | "Timeline"
  | "Grid"
  | "Flow"
  | "MindMap"
  | { "Custom": string };
