// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderedListStyle } from "./OrderedListStyle";
import type { UnorderedListStyle } from "./UnorderedListStyle";

export type ListStyle = { "Unordered": UnorderedListStyle } | {
  "Ordered": OrderedListStyle;
};
