// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionContentNode } from "./SectionContentNode";

export type ListItemNode = {
  /**
   * Content of a list item can be complex, allowing nested structures.
   */
  content: Array<SectionContentNode>;
};
