// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListItemNode } from "./ListItemNode";
import type { ListStyle } from "./ListStyle";

export type ListNode = {
  items: Array<ListItemNode>;
  style: ListStyle;
  start_index: number | null;
};
