// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllowedInteraction } from "./AllowedInteraction";
import type { ExtractionMetadata } from "./ExtractionMetadata";
import type { InteractionLevel } from "./InteractionLevel";
import type { ViewportConfig } from "./ViewportConfig";

export type LiveEmbedContent = {
  source_document_id: string;
  sync_with_source: boolean;
  allowed_interactions: Array<AllowedInteraction>;
  extraction_metadata: ExtractionMetadata;
  viewport_config: ViewportConfig;
  interaction_level: InteractionLevel;
};
