// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrowStyle } from "./ArrowStyle";

export type MappingArrow = {
  from: string;
  to: string;
  arrow_style: ArrowStyle;
  label: string | null;
};
