// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MappingArrow } from "./MappingArrow";
import type { VisualizationType } from "./VisualizationType";

export type MappingVisualization = {
  visualization_type: VisualizationType;
  source_elements: Array<string>;
  target_elements: Array<string>;
  mapping_arrows: Array<MappingArrow>;
};
