// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";
import type { UnificationDetail } from "./UnificationDetail";

/**
 * Display representation of match verification
 */
export type MatchVerification = {
  pattern: MathNode;
  target: MathNode;
  match_success: boolean;
  match_explanation: RichText;
  unification_details: Array<UnificationDetail>;
};
