// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentMetadata } from "./ContentMetadata";
import type { DocumentRelationships } from "./DocumentRelationships";
import type { DocumentStructure } from "./DocumentStructure";
import type { FormalityLevel } from "./FormalityLevel";

export type MathematicianNotesContent = {
  title: string;
  research_area: string;
  formality_level: FormalityLevel;
  content_metadata: ContentMetadata;
  structure: DocumentStructure;
  relationships: DocumentRelationships;
};
