// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { TextStyle } from "./TextStyle";

/**
 * Simple text segments for mathematical expressions
 */
export type MathTextSegment = { "Text": string } | { "Math": MathNode } | {
  "StyledText": { text: string; styles: Array<TextStyle> };
};
