// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathObjectMetadata } from "./MathObjectMetadata";

/**
 * A module to organize mathematical content
 */
export type MathModule = {
  /**
   * Metadata for the module
   */
  metadata: MathObjectMetadata;
  /**
   * Submodules contained within this module
   */
  submodules: Array<string> | null;
  /**
   * Definitions included in this module
   */
  definitions: Array<string> | null;
  /**
   * Theorems included in this module
   */
  theorems: Array<string> | null;
  /**
   * Examples included in this module
   */
  examples: Array<string> | null;
  /**
   * Learning objectives for this module
   */
  learning_objectives: Array<string> | null;
};
