// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BibEntryNode } from "./BibEntryNode";
import type { Section } from "./Section";
import type { SectionContentNode } from "./SectionContentNode";
import type { StructuredMathContentNode } from "./StructuredMathContentNode";
import type { TocNode } from "./TocNode";

/**
 * Represents the root of a math document or page.
 */
export type MathDocument = {
  id: string;
  title: string;
  language: string | null;
  version: string | null;
  authors: Array<string> | null;
  date_published: string | null;
  date_modified: string | null;
  abstract_content: Array<SectionContentNode> | null;
  table_of_contents: TocNode | null;
  body: Array<Section>;
  footnotes: Array<[string, Array<SectionContentNode>]> | null;
  glossary: Array<[string, StructuredMathContentNode]> | null;
  bibliography: Array<[string, BibEntryNode]> | null;
  document_metadata: Array<[string, string]> | null;
};
