// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathematicalContentType } from "./MathematicalContentType";

/**
 * The main container for mathematical content with a unique ID and content type
 */
export type MathematicalContent = {
  id: string;
  content_type: MathematicalContentType;
};
