// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Common metadata for all mathematical objects
 */
export type MathObjectMetadata = {
  /**
   * Unique identifier for the object
   */
  id: string;
  /**
   * Display name for the object
   */
  name: string;
  /**
   * Domain the object belongs to (e.g., "zfc", "groups")
   */
  domain: string;
  /**
   * Type of the object within its domain (e.g., "set", "axiom", "theorem")
   */
  object_type: string;
  /**
   * Short description of the object
   */
  description: string;
  /**
   * When the object was first created/discovered (if applicable)
   */
  discovery_date: string | null;
  /**
   * Who discovered/created the object (if applicable)
   */
  discoverer: string | null;
  /**
   * Importance level (1-5, with 5 being most important)
   */
  importance: number;
  /**
   * Difficulty level (1-5, with 5 being most difficult)
   */
  difficulty: number;
  /**
   * Tags for categorization
   */
  tags: Array<string>;
  /**
   * LaTeX representation if applicable
   */
  latex: string | null;
};
