// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of nodes in branching containers
 */
export type NodeType =
  | "ProofGoal"
  | "ProofStep"
  | "ProofManager"
  | "ProofCompleted"
  | "ProofDisproved"
  | "StoryScene"
  | "Character"
  | "Event"
  | "Timeline"
  | "Branch"
  | "Leaf"
  | "Decision"
  | "Outcome"
  | { "Custom": string };
