// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of numbers
 */
export type NumberType =
  | "Integer"
  | "Rational"
  | "Real"
  | "Complex"
  | "Natural";
