// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of mathematical operations
 */
export type OperationType =
  | "Addition"
  | "Subtraction"
  | "Multiplication"
  | "Division"
  | "Power"
  | "Inverse"
  | "Composition"
  | "GroupOperation"
  | "SetUnion"
  | "SetIntersection"
  | "SetDifference";
