// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PanelControls = {
  allow_minimize: boolean | null;
  allow_close: boolean | null;
  allow_reorder: boolean | null;
};
