// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PanelLayoutType =
  | "Tabs"
  | "Accordion"
  | { "Grid": { columns: number } }
  | { "Sidebar": { main_panel_id: string } }
  | "FloatingPanels";
