// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Panel } from "./Panel";
import type { PanelControls } from "./PanelControls";
import type { PanelLayoutType } from "./PanelLayoutType";

export type PanelLayout = {
  panels: Array<Panel>;
  layout_type: PanelLayoutType;
  panel_controls: PanelControls | null;
};
