// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanelRole } from "./PanelRole";
import type { RichText } from "./RichText";
import type { SectionContentNode } from "./SectionContentNode";

export type Panel = {
  id: string;
  title: RichText | null;
  content: Array<SectionContentNode>;
  panel_role: PanelRole;
  initially_visible: boolean | null;
  resizable: boolean | null;
};
