// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichTextSegment } from "./RichTextSegment";
import type { TextAlignment } from "./TextAlignment";

/**
 * Represents a paragraph of rich text.
 */
export type ParagraphNode = {
  segments: Array<RichTextSegment>;
  alignment: TextAlignment | null;
};
