// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Constraint } from "./Constraint";
import type { Parameter } from "./Parameter";

export type ParameterSpace = {
  parameters: Array<Parameter>;
  constraints: Array<Constraint>;
  default_values: { [key in string]?: number };
};
