// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParameterType =
  | "Continuous"
  | "Discrete"
  | "Integer"
  | "Boolean"
  | { "Categorical": { options: Array<string> } };
