// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParameterRange } from "./ParameterRange";
import type { ParameterType } from "./ParameterType";

export type Parameter = {
  name: string;
  parameter_type: ParameterType;
  range: ParameterRange;
  description: string | null;
};
