// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a pattern match between expressions
 */
export type PatternMatch = {
  pattern_id: string;
  source_expression: string;
  matched_expression: string;
  confidence: number;
  substitution_map: { [key in string]?: string };
};
