// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudienceLevel } from "./AudienceLevel";
import type { ContentMetadata } from "./ContentMetadata";
import type { DocumentRelationships } from "./DocumentRelationships";
import type { DocumentStructure } from "./DocumentStructure";
import type { NoteStyle } from "./NoteStyle";

export type PersonalNotesContent = {
  title: string;
  author_level: AudienceLevel;
  note_style: NoteStyle;
  content_metadata: ContentMetadata;
  structure: DocumentStructure;
  relationships: DocumentRelationships;
};
