// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationConfig } from "./AnimationConfig";
import type { AudienceLevel } from "./AudienceLevel";
import type { FormalityLevel } from "./FormalityLevel";
import type { InteractionFeature } from "./InteractionFeature";
import type { LayoutStyle } from "./LayoutStyle";

export type PresentationConfig = {
  layout_style: LayoutStyle;
  interaction_features: Array<InteractionFeature>;
  target_audience: AudienceLevel;
  formality_level: FormalityLevel;
  animation_config: AnimationConfig | null;
};
