// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParagraphNode } from "./ParagraphNode";
import type { ProofDisplayNode } from "./ProofDisplayNode";

export type ProofCaseNode = {
  condition: ParagraphNode;
  proof_for_case: ProofDisplayNode;
};
