// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visual styles for proof elements
 */
export type ProofVisualStyle =
  | "Minimal"
  | "Standard"
  | "Detailed"
  | "Interactive"
  | "Animated";
