// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color scheme for proof visualization
 */
export type ProofColorScheme = {
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  success_color: string;
  error_color: string;
  warning_color: string;
  info_color: string;
};
