// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofDisplayNode } from "./ProofDisplayNode";
import type { RichText } from "./RichText";

/**
 * Represents a case in case analysis
 */
export type ProofCaseNode = {
  condition: RichText;
  proof_for_case: ProofDisplayNode;
};
