// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DomainReference } from "./DomainReference";
import type { ProofStep } from "./ProofStep";

/**
 * A mathematical proof
 */
export type Proof = {
  /**
   * Method of proof (direct, contradiction, induction, etc.)
   */
  method: string;
  /**
   * Sequence of steps in the proof
   */
  steps: Array<ProofStep>;
  /**
   * Key insights that make the proof work
   */
  key_insights: Array<string>;
  /**
   * Alternative approaches that could be used
   */
  alternative_approaches: Array<string> | null;
  /**
   * References to other mathematical objects used in the proof
   */
  references: Array<DomainReference>;
};
