// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofStepDisplay } from "./ProofStepDisplay";

/**
 * Represents a display-oriented proof structure with tree-like branching.
 */
export type ProofNodeDisplay = {
  step: ProofStepDisplay;
  /**
   * Child proof branches - for representing proof tree structure
   */
  children: Array<ProofNodeDisplay>;
};
