// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationData } from "./AnimationData";
import type { DomainReference } from "./DomainReference";

/**
 * A single step in a mathematical proof
 */
export type ProofStep = {
  /**
   * Step number in the proof
   */
  step_number: number;
  /**
   * Description of the step
   */
  description: string;
  /**
   * LaTeX representation of the step
   */
  latex: string;
  /**
   * Justification for this step (e.g., "By Axiom 3", "From steps 2 and 4")
   */
  justification: string;
  /**
   * Optional animation data for visualizing this step
   */
  animation: AnimationData | null;
  /**
   * References to other mathematical objects used in this step
   */
  references: Array<DomainReference> | null;
};
