// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParagraphNode } from "./ParagraphNode";
import type { ProofStepNode } from "./ProofStepNode";
import type { SectionContentNode } from "./SectionContentNode";

/**
 * Represents a display-oriented proof structure.
 */
export type ProofDisplayNode = {
  title: ParagraphNode | null;
  strategy: Array<SectionContentNode> | null;
  steps: Array<ProofStepNode>;
  qed_symbol: string | null;
};
