// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Layout types for proof visualization
 */
export type ProofLayoutType =
  | "Tree"
  | "Linear"
  | "Graph"
  | "Timeline"
  | "OmniOutliner";
