// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofLayoutType } from "./ProofLayoutType";
import type { ProofNodeDisplay } from "./ProofNodeDisplay";
import type { ProofVisualStyle } from "./ProofVisualStyle";

/**
 * Display container for proof forest visualization
 */
export type ProofForestDisplay = {
  forest_id: string;
  root_nodes: Array<ProofNodeDisplay>;
  layout_type: ProofLayoutType;
  visual_style: ProofVisualStyle;
};
