// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofColorScheme } from "./ProofColorScheme";
import type { ProofLayoutType } from "./ProofLayoutType";
import type { ProofVisualStyle } from "./ProofVisualStyle";

/**
 * Configuration for proof visualization
 */
export type ProofVisualConfig = {
  layout_type: ProofLayoutType;
  visual_style: ProofVisualStyle;
  animation_enabled: boolean;
  show_connections: boolean;
  show_interactive_elements: boolean;
  color_scheme: ProofColorScheme;
};
