// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionHandler } from "./InteractionHandler";

/**
 * Configuration for proof interactions
 */
export type ProofInteractionConfig = {
  allow_click_interactions: boolean;
  allow_hover_interactions: boolean;
  allow_drag_interactions: boolean;
  allow_selection: boolean;
  allow_highlighting: boolean;
  interaction_handlers: Array<InteractionHandler>;
};
