// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Visual state of a proof node
 */
export type ProofNodeVisualState =
  | "Normal"
  | "Highlighted"
  | "Selected"
  | "Active"
  | "Completed"
  | "Error";
