// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofStepNode } from "./ProofStepNode";
import type { RichText } from "./RichText";
import type { SectionContentNode } from "./SectionContentNode";

/**
 * Represents a display-oriented proof structure (for frontend compatibility)
 */
export type ProofDisplayNode = {
  title: RichText | null;
  strategy: Array<SectionContentNode>;
  steps: Array<ProofStepNode>;
  qed_symbol: string | null;
};
