// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { ProofDisplayNode } from "./ProofDisplayNode";

/**
 * Structured proof case
 */
export type ProofCase = {
  condition: MathNode;
  proof: ProofDisplayNode;
  case_name: string | null;
};
