// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Simple representation of what changed in a ProofGoal after a tactic
 */
export type ProofGoalChange = {
  /**
   * Names of quantifiers that were added/removed/modified
   */
  quantifier_changes: Array<string>;
  /**
   * Names of value variables that were added/removed/modified
   */
  variable_changes: Array<string>;
  /**
   * Whether the main statement changed
   */
  statement_changed: boolean;
  /**
   * Summary of the change
   */
  summary: string;
};
