// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of interaction available for expressions
 */
export type ProofExpressionInteractionType =
  | "Highlightable"
  | "Selectable"
  | "PatternMatchable"
  | "Transformable"
  | "Clickable"
  | "Draggable";
