// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of proof steps
 */
export type ProofStepStatus =
  | "Complete"
  | "InProgress"
  | "Todo"
  | "WorkInProgress"
  | "Abandoned";
