// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalDisplay } from "./GoalDisplay";
import type { ProofNodeVisualState } from "./ProofNodeVisualState";
import type { TacticDisplay } from "./TacticDisplay";
import type { TransformationDisplay } from "./TransformationDisplay";

/**
 * Display container for individual proof node
 */
export type ProofNodeDisplay = {
  node_id: string;
  step_number: number;
  tactic_display: TacticDisplay;
  goal_display: GoalDisplay;
  transformation_display: TransformationDisplay | null;
  children: Array<ProofNodeDisplay>;
  visual_state: ProofNodeVisualState;
};
