// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { QuantifierType } from "./QuantifierType";

/**
 * Represents a quantified mathematical object in structured form
 */
export type QuantifiedObject = {
  variable: string;
  quantification: QuantifierType;
  object_type: string;
  constraints: Array<MathNode>;
  description: string | null;
};
