// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Types of quantification
 */
export type QuantifierType =
  | "Universal"
  | "Existential"
  | "UniqueExistential"
  | "Defined"
  | "Fixed";
