// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuantifierType } from "./QuantifierType";
import type { SecondOrderMathNode } from "./SecondOrderMathNode";

export type QuantifierGroup = {
  quantifier_type: QuantifierType;
  variables: Array<SecondOrderMathNode>;
};
