// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Type of reference between mathematical objects
 */
export type ReferenceType =
  | "Definition"
  | "Theorem"
  | "Axiom"
  | "Example"
  | "SpecialCase"
  | "Generalization"
  | "Application";
