// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DivSymbol } from "./DivSymbol";
import type { MulSymbol } from "./MulSymbol";

export type RefinedMulOrDivOperation = { "Multiplication": MulSymbol } | { "Division": DivSymbol } | "None";
