// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelationOperator = "IsEqual" | "Equal" | "NotEqual" | "Greater" | "Less" | "GreaterEqual" | "LessEqual" | "Collinear" | "Perpendicular" | "Equivalent" | "Similar" | "Congruent";
