// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RelationshipMetadata = {
  relationship_type: string;
  strength: number | null;
  bidirectional: boolean | null;
  properties: { [key in string]?: string };
};
