// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceType } from "./ResourceType";

export type ResourceItem = {
  id: string;
  title: string;
  description: string | null;
  resource_type: ResourceType;
  link: string | null;
};
