// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceItem } from "./ResourceItem";

export type ResourceCategory = {
  name: string;
  icon: string | null;
  color: string | null;
  items: Array<ResourceItem>;
};
