// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Display representation of rewrite direction
 */
export type RewriteDirectionDisplay = {
  "LeftToRight": {
    left_side: MathNode;
    right_side: MathNode;
    explanation: RichText;
  };
} | {
  "RightToLeft": {
    left_side: MathNode;
    right_side: MathNode;
    explanation: RichText;
  };
};
