// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Display representation of rewrite steps
 */
export type RewriteStep = {
  step_number: number;
  before: MathNode;
  after: MathNode;
  rule_applied: RichText;
  explanation: RichText;
  highlighted_region: Array<number> | null;
};
