// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkTarget } from "./LinkTarget";
import type { MathNode } from "./MathNode";
import type { TextStyle } from "./TextStyle";

/**
 * Represents a segment of rich text, allowing for mixed content within paragraphs, list items, etc.
 */
export type RichTextSegment =
  | { "Text": string }
  | { "StyledText": { text: string; styles: Array<TextStyle> } }
  | { "Math": MathNode }
  | {
    "Link": {
      /**
       * The visible content of the link, can be rich text itself.
       */
      content: Array<RichTextSegment>;
      target: LinkTarget;
      tooltip: string | null;
    };
  }
  | { "FootnoteReference": string }
  | { "CodeInline": string };
