// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SandboxPermission = {
  permission_type: string;
  allowed: boolean;
  restrictions: Array<string> | null;
};
