// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";

export type ScriptNode = {
  subscripts: Array<MathNode>;
  superscripts: Array<MathNode>;
};
