// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { SearchNodeDisplay } from "./SearchNodeDisplay";

/**
 * Display representation of search tree for automated tactics
 */
export type SearchTreeDisplay = {
  root_goal: MathNode;
  search_nodes: Array<SearchNodeDisplay>;
  successful_path: Array<number>;
  max_depth_reached: number;
};
