// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortOption } from "./SortOption";

export type SearchCapabilities = {
  full_text_search: boolean;
  semantic_search: boolean;
  filter_by_type: boolean;
  sort_options: Array<SortOption>;
};
