// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Individual node in search tree
 */
export type SearchNodeDisplay = {
  node_id: number;
  parent_id: number | null;
  goal_state: MathNode;
  tactic_applied: RichText | null;
  success: boolean;
  children: Array<number>;
};
