// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Judgement } from "./Judgement";
import type { LogicalNode } from "./LogicalNode";
import type { MathNode } from "./MathNode";
import type { QuantifiedVariableDeclarationGroup } from "./QuantifiedVariableDeclarationGroup";
import type { Solution } from "./Solution";
import type { VariableDeclaration } from "./VariableDeclaration";

/**
 * This matches the TypeScript StructuredMathNode bindings
 */
export type SecondOrderMathNode =
  | { "Logic": LogicalNode }
  | { "Judgement": Judgement }
  | { "SystemOf": Array<MathNode> }
  | { "Solution": Solution }
  | { "VariableDeclaration": VariableDeclaration }
  | {
    "QuantifiedVariableDeclarationGroup": QuantifiedVariableDeclarationGroup;
  };
