// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";
import type { SectionContentNode } from "./SectionContentNode";
import type { SectionDisplayOptions } from "./SectionDisplayOptions";

/**
 * A `SectionNode` represents a major, navigable part of a document (like a chapter or a named section).
 * It can have a title and contains various content blocks. Sections can be nested.
 */
export type Section = {
  id: string;
  title: RichText | null;
  content: SectionContentNode;
  metadata: Array<[string, string]>;
  display_options: SectionDisplayOptions | null;
};
