// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParagraphNode } from "./ParagraphNode";
import type { SectionContentNode } from "./SectionContentNode";
import type { SectionDisplayOptions } from "./SectionDisplayOptions";

/**
 * A `SectionNode` represents a major, navigable part of a document (like a chapter or a named section).
 * It can have a title and contains various content blocks. Sections can be nested.
 */
export type Section = {
  id: string;
  title: ParagraphNode | null;
  content: Array<SectionContentNode>;
  sub_sections: Array<Section>;
  metadata: Array<[string, string]> | null;
  display_options: SectionDisplayOptions | null;
};
