// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a property that can have selectable variants in the UI.
 */
export type SelectableProperty = {
  name: string;
  current_variant: string;
  all_variants: Array<string>;
  description: string | null;
  variant_descriptions: { [key in string]?: string } | null;
  property_type_def_id: string | null;
};
