// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SideBySideConfig = {
  left_width: string | null;
  right_width: string | null;
  gap: string | null;
  responsive_breakpoint: string | null;
};
