// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Panel } from "./Panel";
import type { SideBySideConfig } from "./SideBySideConfig";

export type SideBySideLayout = {
  left_panel: Panel;
  right_panel: Panel;
  sync_scrolling: boolean | null;
  highlight_correspondence: boolean | null;
  layout_config: SideBySideConfig | null;
};
