// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";

/**
 * Display representation of simplification steps
 */
export type SimplificationStep = {
  step_number: number;
  before: MathNode;
  after: MathNode;
  rule_name: RichText;
  rule_explanation: RichText;
  algebraic_justification: RichText | null;
};
