// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConceptRelationship } from "./ConceptRelationship";
import type { CoreExample } from "./CoreExample";
import type { EssentialDefinition } from "./EssentialDefinition";
import type { KeyPoint } from "./KeyPoint";

export type SimplifiedContentStructure = {
  key_points: Array<KeyPoint>;
  essential_definitions: Array<EssentialDefinition>;
  core_examples: Array<CoreExample>;
  concept_relationships: Array<ConceptRelationship>;
};
