// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivationMethod } from "./DerivationMethod";

export type SourceReference = {
  source_id: string;
  source_type: string;
  specific_sections: Array<string>;
  derivation_method: DerivationMethod;
  confidence_level: number;
};
