// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecialMiddleScriptContentType } from "./SpecialMiddleScriptContentType";

export type SpecialMiddleScript = { super_script: Array<SpecialMiddleScriptContentType>, sub_script: Array<SpecialMiddleScriptContentType>, };
