// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecialMiddleScriptContentTypeNode } from "./SpecialMiddleScriptContentTypeNode";

export type SpecialMiddleScriptNode = {
  super_script: Array<SpecialMiddleScriptContentTypeNode>;
  sub_script: Array<SpecialMiddleScriptContentTypeNode>;
};
