// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionMetadata } from "./ExtractionMetadata";
import type { InteractionLevel } from "./InteractionLevel";
import type { SimplifiedContentStructure } from "./SimplifiedContentStructure";
import type { ViewportConfig } from "./ViewportConfig";

export type StaticPreviewContent = {
  source_document_id: string;
  content_snapshot: SimplifiedContentStructure;
  last_updated: string;
  auto_refresh: boolean;
  extraction_metadata: ExtractionMetadata;
  viewport_config: ViewportConfig;
  interaction_level: InteractionLevel;
};
