// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StateVariableType } from "./StateVariableType";

export type StateVariable = {
  name: string;
  initial_value: string;
  variable_type: StateVariableType;
};
