// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";

/**
 * Highlight information for substitutions
 */
export type SubstitutionHighlight = {
  path: Array<number>;
  original_text: RichText;
  replacement_text: RichText;
  explanation: RichText | null;
};
