// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncType } from "./SyncType";

export type SyncGroup = {
  group_id: string;
  elements: Array<string>;
  sync_type: SyncType;
};
