// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnStyle } from "./ColumnStyle";
import type { ParagraphNode } from "./ParagraphNode";
import type { TableRowNode } from "./TableRowNode";
import type { TableStyleOptions } from "./TableStyleOptions";

export type TableNode = {
  caption: ParagraphNode | null;
  header_rows: Array<TableRowNode> | null;
  body_rows: Array<TableRowNode>;
  footer_rows: Array<TableRowNode> | null;
  column_styles: Array<ColumnStyle> | null;
  table_style_options: TableStyleOptions | null;
};
