// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SectionContentNode } from "./SectionContentNode";
import type { TableCellType } from "./TableCellType";
import type { TextAlignment } from "./TextAlignment";

export type TableCellNode = {
  content: Array<SectionContentNode>;
  col_span: number | null;
  row_span: number | null;
  cell_type: TableCellType;
  alignment: TextAlignment | null;
};
