// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TacticVisualStyle } from "./TacticVisualStyle";
import type { TransformationWorkflowStage } from "./TransformationWorkflowStage";

/**
 * Display container for tactic information
 */
export type TacticDisplay = {
  tactic_name: string;
  tactic_type: string;
  description: string;
  interactive_elements: Array<string>;
  workflow_stage: TransformationWorkflowStage;
  visual_style: TacticVisualStyle;
};
