// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TextStyle =
  | "Bold"
  | "Italic"
  | "Underline"
  | "Strikethrough"
  | "Superscript"
  | "Subscript"
  | { "Color": string }
  | { "BackgroundColor": string }
  | { "FontSize": string }
  | { "FontFamily": string };
