// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcademicMetadata } from "./AcademicMetadata";
import type { ChapterInfo } from "./ChapterInfo";
import type { ContentMetadata } from "./ContentMetadata";
import type { CourseLevel } from "./CourseLevel";
import type { DocumentRelationships } from "./DocumentRelationships";
import type { DocumentStructure } from "./DocumentStructure";

export type TextbookContent = {
  title: string;
  course_level: CourseLevel;
  chapter_info: ChapterInfo | null;
  prerequisites: Array<string>;
  content_metadata: ContentMetadata;
  academic_metadata: AcademicMetadata;
  structure: DocumentStructure;
  relationships: DocumentRelationships;
};
