// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TheoryReference = {
  theory_id: string;
  theory_name: string;
  version: string | null;
};
