// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkTarget } from "./LinkTarget";
import type { RichText } from "./RichText";

/**
 * Reference to a theorem
 */
export type TheoremReference = {
  theorem_id: string;
  theorem_name: RichText;
  theorem_statement: RichText;
  relevance_score: number | null;
  link: LinkTarget | null;
};
