// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { SectionContentNode } from "./SectionContentNode";

/**
 * Represents different ways a theorem statement can be expressed
 */
export type TheoremStatement = { "Content": Array<SectionContentNode> } | {
  "Mathematical": MathNode;
};
