// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TocNode = {
  title: string;
  target_id: string;
  children: Array<TocNode>;
};
