// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivationMetadata } from "./DerivationMetadata";
import type { PresentationConfig } from "./PresentationConfig";
import type { SimplifiedContentStructure } from "./SimplifiedContentStructure";
import type { SourceReference } from "./SourceReference";
import type { SummarizationLevel } from "./SummarizationLevel";

export type TooltipSummaryContent = {
  summarization_level: SummarizationLevel;
  max_length: number | null;
  focus_concepts: Array<string>;
  source_references: Array<SourceReference>;
  derivation_metadata: DerivationMetadata;
  content: SimplifiedContentStructure;
  presentation_config: PresentationConfig;
};
