// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Animation configuration for transformations
 */
export type TransformationAnimationConfig = {
  duration_ms: number;
  easing: string;
  show_progress: boolean;
  highlight_source: boolean;
  highlight_target: boolean;
  show_connections: boolean;
};
