// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelationshipMetadata } from "./RelationshipMetadata";
import type { TheoryReference } from "./TheoryReference";
import type { TransformationStep } from "./TransformationStep";
import type { TransformationType } from "./TransformationType";

export type TransformationMappingContent = {
  title: string;
  transformation_type: TransformationType;
  step_by_step: boolean;
  bidirectional: boolean;
  source_theory: string;
  target_theory: string;
  transformation_steps: Array<TransformationStep>;
  theories_involved: Array<TheoryReference>;
  relationship_metadata: RelationshipMetadata;
};
