// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the workflow stages in a proof transformation
 */
export type TransformationWorkflowStage =
  | "Prescribe"
  | "Search"
  | "Instantiate"
  | "Replace"
  | "Verify";
