// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstantiationMap } from "./InstantiationMap";
import type { InteractiveElement } from "./InteractiveElement";
import type { InteractiveExpression } from "./InteractiveExpression";
import type { PatternMatch } from "./PatternMatch";
import type { TransformationAnimationConfig } from "./TransformationAnimationConfig";
import type { VisualConnection } from "./VisualConnection";

/**
 * Display container for transformation visualization
 */
export type TransformationDisplay = {
  source_expressions: Array<InteractiveExpression>;
  target_expressions: Array<InteractiveExpression>;
  pattern_matches: Array<PatternMatch>;
  instantiations: Array<InstantiationMap>;
  visual_connections: Array<VisualConnection>;
  interactive_elements: Array<InteractiveElement>;
  animation_config: TransformationAnimationConfig | null;
};
