// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisualConnection } from "./VisualConnection";

/**
 * Represents the visual flow of a tactic transformation
 */
export type TransformationFlow = {
  tactic_type: string;
  direction: string;
  source_elements: Array<string>;
  target_elements: Array<string>;
  transformation_type: string;
  visual_connections: Array<VisualConnection>;
};
