// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichTextSegment } from "./RichTextSegment";

export type TransformationStep = {
  step_number: number;
  description: Array<RichTextSegment>;
  source_concept: string;
  target_concept: string;
  transformation_rule: string;
  visual_representation: string | null;
  interactive_demo: string | null;
};
