// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";

export type TurnTextLineNode =
  | { "Math": [MathNode, string] }
  | { "Phrase": string }
  | "Empty"
  | { "Comment": string }
  | { "Latex": string }
  | { "PageLink": string }
  | { "Image": string };
