// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationTimeline } from "./AnimationTimeline";
import type { ControlBinding } from "./ControlBinding";
import type { InteractionSystem } from "./InteractionSystem";
import type { MappingVisualization } from "./MappingVisualization";
import type { Section } from "./Section";

export type TypeMappingDisplayContent = {
  title: string;
  source_theory: string;
  target_theory: string;
  mapping_visualizations: Array<MappingVisualization>;
  base_content: Array<Section>;
  interaction_system: InteractionSystem;
  animation_timeline: AnimationTimeline | null;
  control_bindings: Array<ControlBinding>;
};
