// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";
import type { RichText } from "./RichText";
import type { UnificationType } from "./UnificationType";

/**
 * Details of unification in pattern matching
 */
export type UnificationDetail = {
  pattern_part: MathNode;
  target_part: MathNode;
  unification_type: UnificationType;
  explanation: RichText;
};
