// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BaseUnitTypeNode } from "./BaseUnitTypeNode";
import type { MathNode } from "./MathNode";

export type UnitComponent = {
  "BaseUnit": { name: BaseUnitTypeNode; prefix: string | null };
} | { "CompoundUnit": { components: Array<[UnitComponent, MathNode]> } };
