// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display representation of variable binding types
 */
export type VariableBindingType =
  | "Assumption"
  | "Definition"
  | "Hypothesis"
  | "Given"
  | "Let";
