// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindingType } from "./BindingType";
import type { MathNode } from "./MathNode";

/**
 * Represents a variable binding in structured form
 */
export type VariableBinding = {
  variable_name: string;
  value: MathNode;
  binding_type: BindingType;
};
