// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MathNode } from "./MathNode";

export type VariableDeclaration = { name: MathNode; type_info: MathNode };
