// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScrollBehavior } from "./ScrollBehavior";

export type ViewportConfig = {
  width: string | null;
  height: string | null;
  responsive: boolean | null;
  scroll_behavior: ScrollBehavior | null;
  zoom_level: number | null;
};
