// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a visual connection between elements in a transformation
 */
export type VisualConnection = {
  from: string;
  to: string;
  connection_type: string;
  style: string;
};
