// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletenessLevel } from "./CompletenessLevel";
import type { ContentMetadata } from "./ContentMetadata";
import type { DocumentRelationships } from "./DocumentRelationships";
import type { DocumentStructure } from "./DocumentStructure";

export type WikiPageContent = {
  title: string;
  theory_domain: string;
  completeness_level: CompletenessLevel;
  maintainer: string | null;
  content_metadata: ContentMetadata;
  structure: DocumentStructure;
  relationships: DocumentRelationships;
};
